const {scraper} = require('./scraper');
const {scraper2} = require('./scraper2');
const {scraper3} = require('./scraper3');
const {scraper4} = require('./scraper4');
const {scraper5} = require('./scraper5');
const {scraper6} = require('./scraper6');
const {scraper7} = require('./scraper7');
const {scraper8} = require('./scraper8');
const {scraper9} = require('./scraper9');
const {scraper10} = require('./scraper10');
const {scraper11} = require('./scraper11');
const {scraper12} = require('./scraper12');
const {scraper13} = require('./scraper13');
const {YCscrape} = require('./YCscrape');
const {APscrape} = require('./APscrape');
const {AAscrape} = require('./AAscrape');
const {ALscrape} = require('./ALscrape');
const {Lscrape} = require('./Lscrape');
const {Bscrape} = require('./Bscrape');
const {server}=require('./server');

server();